const actions = {
  GET_FLIGHT_LIST: "GET_FLIGHT_LIST",
  GET_FLIGHT_LIST_SUCCESS: "GET_FLIGHT_LIST_SUCCESS",
  GET_FLIGHT_LIST_ERROR: "GET_FLIGHT_LIST_ERROR",
  RESET_FLIGHT_LIST: "RESET_FLIGHT_LIST",

  SET_BOOKING_DETAILS: "SET_BOOKING_DETAILS"
};

export default actions;
